version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      # Exclude vendor directory from the mount to preserve the one in the container
      - /app/vendor
    environment:
      - PORT=8000 