version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      # Exclude vendor directory from the mount to preserve the one in the container
      - /app/vendor
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://janedoe:mypassword@postgres:5432/mydb
    depends_on:
      - postgres
    # Add healthcheck to ensure the application is running correctly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: janedoe
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount database.sql to be executed on container initialization
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    # Add healthcheck for PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U janedoe -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 