<div class="container-lg mt-5">
    <h1>Сайты</h1>

    <div class="table-responsive">
        <table class="table table-bordered table-hover" data-test="urls">
            <thead>
                <tr>
                    <th class="col-1">ID</th>
                    <th>Имя</th>
                    <th class="col-2">Последняя проверка</th>
                    <th class="col-1">Код ответа</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($urls as $url): ?>
                    <tr>
                        <td><?= $url['id'] ?></td>
                        <td>
                            <a href="/urls/<?= $url['id'] ?>"><?= htmlspecialchars($url['name']) ?></a>
                        </td>
                        <td>
                            <?= isset($url['last_check_created_at']) ? $url['last_check_created_at'] : '' ?>
                        </td>
                        <td>
                            <?php if (isset($url['last_check_status_code'])): ?>
                                <span class="badge <?= $url['last_check_status_code'] < 400 ? 'bg-success' : 'bg-danger' ?>">
                                    <?= $url['last_check_status_code'] ?>
                                </span>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div> 