<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page Analyzer</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body class="d-flex flex-column min-vh-100">
    <header class="navbar navbar-expand-md navbar-dark bg-dark mb-3">
        <div class="container">
            <a class="navbar-brand" href="/">Page Analyzer</a>
        </div>
    </header>

    <main class="flex-grow-1">
        <div class="container mt-4">
            <div class="row">
                <div class="col-md-10 col-lg-8 mx-auto">
                    <h1 class="display-3 mb-3">Page Analyzer</h1>
                    <p class="lead">Check web pages for SEO suitability</p>
                    
                    <form action="/analyze" method="post" class="mt-3 mb-5">
                        <div class="input-group mb-3">
                            <input type="text" class="form-control form-control-lg" id="url" name="url" placeholder="https://example.com" required>
                            <button type="submit" class="btn btn-primary btn-lg ms-3 px-5">Check</button>
                        </div>
                    </form>
                    
                    <?php if (isset($messages)): ?>
                        <?php foreach ($messages as $message): ?>
                            <div class="alert alert-<?= $message['type'] ?>" role="alert">
                                <?= $message['text'] ?>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </main>

    <footer class="footer border-top py-3 mt-5 bg-light">
        <div class="container-lg">
            <div class="text-center">
                <p>© 2023 Page Analyzer</p>
            </div>
        </div>
    </footer>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html> 