<div class="container-lg mt-5">
    <div class="row">
        <div class="col-12 col-md-10 col-lg-8 mx-auto">
            <h1 class="display-3">Анализатор страниц</h1>
            <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
            
            <form action="/urls" method="post" class="mt-3 mb-3">
                <div class="row">
                    <div class="col">
                        <div class="form-floating">
                            <input 
                                type="text" 
                                class="form-control <?= isset($errors['url']) ? 'is-invalid' : '' ?>" 
                                id="url-input" 
                                name="url[name]" 
                                placeholder="https://www.example.com" 
                                required
                            >
                            <label for="url-input">Url для проверки</label>
                            <?php if (isset($errors['url'])): ?>
                                <div class="invalid-feedback">
                                    <?= $errors['url'] ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-primary btn-lg px-5">Проверить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div> 